const Map<String, List<String>> disorderSymptoms = {
  'Migraine': [
    'Headache',
    'Nausea',
    'Vomiting',
    'Light sensitivity',
    'Sound sensitivity',
    'Visual aura',
    'Neck pain',
    'Dizziness',
    'Brain fog',
    'Fatigue',
  ],
  'Dysautonomia': [
    'Dizziness',
    'Light-headedness',
    'Palpitations',
    'Fatigue',
    'Brain fog',
    'Shortness of breath',
    'Exercise intolerance',
    'Nausea',
    'Sweating changes',
    'Temperature intolerance',
  ],
  'CIDP': [
    'Weakness',
    'Numbness',
    'Tingling',
    'Pain',
    'Fatigue',
    'Balance problems',
    'Walking difficulty',
    'Hand clumsiness',
    'Falls',
    'Muscle cramps',
  ],
  'Myasthenia Gravis': [
    'Muscle weakness',
    'Double vision',
    'Drooping eyelids',
    'Difficulty swallowing',
    'Slurred speech',
    'Shortness of breath',
    'Chewing fatigue',
    'Neck weakness',
    'Arm weakness',
    'Leg weakness',
  ],
};
